/**
 * Standardised report templates with limited customisation (SRD-G09).
 *
 * Each role gets a curated set of built-in templates that pre-configure the
 * Reports page filters and chart layout. Users can also save their own
 * templates via useReportTemplates() (SRD-U14, SRD-A14).
 */

import type { ReportTemplate } from '@/lib/types/store'

const NOW = '2024-01-01T00:00:00.000Z'

export const BUILT_IN_REPORT_TEMPLATES: ReportTemplate[] = [
  // ─── Customer ───────────────────────────────────────────────────────────────
  {
    id: 'rt-customer-monthly-spend',
    name: 'My Monthly Spending',
    description: 'Last 30 days of spending broken down by category.',
    scope: 'customer',
    builtIn: true,
    config: {
      dateRange: 'last_30_days',
      grouping: 'category',
      chartType: 'pie',
      includeIncome: false,
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'rt-customer-savings-trend',
    name: 'Savings Trend (12 months)',
    description: 'Income vs. spending and resulting savings ratio over a year.',
    scope: 'customer',
    builtIn: true,
    config: {
      dateRange: 'last_12_months',
      grouping: 'month',
      chartType: 'area',
      includeIncome: true,
      showSavingsRatio: true,
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  // ─── Adviser ────────────────────────────────────────────────────────────────
  {
    id: 'rt-fa-client-overview',
    name: 'Client Portfolio Overview',
    description: 'Per-client AUM, risk tier, and 12-month performance.',
    scope: 'fa',
    builtIn: true,
    config: {
      dateRange: 'last_12_months',
      grouping: 'client',
      chartType: 'bar',
      includeBenchmark: true,
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'rt-fa-consultation-load',
    name: 'Consultation Load',
    description: 'Number of consultations per month grouped by topic.',
    scope: 'fa',
    builtIn: true,
    config: {
      dateRange: 'last_6_months',
      grouping: 'consultation_topic',
      chartType: 'line',
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  // ─── Manager ────────────────────────────────────────────────────────────────
  {
    id: 'rt-mgr-team-performance',
    name: 'Team Performance Snapshot',
    description: 'Satisfaction, completion rate and response time across the team.',
    scope: 'manager',
    builtIn: true,
    config: {
      dateRange: 'last_quarter',
      grouping: 'advisor',
      chartType: 'bar',
      metrics: ['satisfactionRate', 'completionRate', 'avgResponseTimeHours'],
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'rt-mgr-quarterly-trend',
    name: 'Quarterly Trend Analysis',
    description: 'Auto-generated quarterly trends across satisfaction, volume, and risk mix.',
    scope: 'manager',
    builtIn: true,
    config: {
      dateRange: 'current_quarter',
      grouping: 'month',
      chartType: 'line',
      metrics: ['satisfactionRate', 'completionRate', 'totalCases'],
      autoGenerated: true,
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
  // ─── Shared ─────────────────────────────────────────────────────────────────
  {
    id: 'rt-shared-export-pack',
    name: 'Standard Export Pack',
    description: 'CSV + PDF export with default columns. Suitable for any role.',
    scope: 'shared',
    builtIn: true,
    config: {
      formats: ['csv', 'pdf'],
      includeFilters: true,
    },
    createdAt: NOW,
    updatedAt: NOW,
  },
]

export function getReportTemplatesForScope(
  scope: ReportTemplate['scope'],
): ReportTemplate[] {
  return BUILT_IN_REPORT_TEMPLATES.filter(
    template => template.scope === scope || template.scope === 'shared',
  )
}
